Fix pacemaker remote 'Illegal relationship operand..' errors
Trying to use a pacemaker remote manifest breaks like this:

Error: Evaluation Error: Illegal relationship operand, can not form a
relationship with an Undef Value. A Catalog type is required. at
/etc/puppet/modules/pacemaker/manifests/remote.pp:31:6 on node

The reason is that the change introduced in
I9511c1830b967038721e03dcbb4401cc3059648a broke the pacemaker remote
functionality.

Let's switch to resource collectors to fix these relationship
issues so we still get the ordering right without the issue:
Debug: /Stage[main]/Pacemaker::Remote/Package[pacemaker-remote]/before: subscribes to File[etc-pacemaker]

Closes-Bug: #1718534

Change-Id: I0b1a5821226491a453b816e3b09369dc4b60d31b