Silence useless facter errors when calling crm_node
When calling crm_node -n we can drop stderr so that people
are not confused about the following error:

$ crm_node -n
error: Could not connect to cluster (is it running?)
$ crm_node -n 2>/dev/null
$

Change-Id: Ie774ff5862cf5f28f712e009d271055eb5d646d0