Fix potential cluster setup race
It seems currently there is a small window for a race opportunity
when we set up the pacemaker cluster with puppet-pacemaker.
The operator will observe the following error:

Error: /Stage[main]/Pacemaker::Corosync/Exec[Start Cluster
tripleo_cluster]/returns: change from notrun to 0 failed:
/sbin/pcs cluster start --all returned 1 instead of one of 0

The following might happen:
On the bootstrap node (where setup_cluster is true) we call
Exec <|tag == 'pacemaker-auth'|> ->
exec {"Create Cluster ${cluster_name}":
  creates => '/etc/cluster/cluster.conf',
  command => "${::pacemaker::pcs_bin} cluster setup --name ${cluster_name} ${cluster_members_rrp_real} ${cluster_setup_extras_real}",
  unless => '/usr/bin/test -f /etc/corosync/corosync.conf',
  require => Class['::pacemaker::install'],
} -> exec {"Start Cluster ${cluster_name}":
  unless => "${::pacemaker::pcs_bin} status >/dev/null 2>&1",
  command => "${::pacemaker::pcs_bin} cluster start --all",
  require => Exec["Create Cluster ${cluster_name}"],
}

The problem with the above is that "pcs cluster setup"
internally will call pcsd.pcsd_sync_certs(...) which will restart pcsd
without waiting. So if we restart pcsd on all nodes and then
jump straift to "pcs cluster start --all" the pcs API call that
starts the cluster on the remote node might happen during the pcsd
restart and hence get a 400 BAD request:
I, [2017-03-29T07:25:00.943344 #15581] INFO -- : CIB USER: hacluster, groups:
Shutting down (TERM)Shutting down (TERM)
[2017-03-29 07:25:09] INFO going to shutdown ...
I, [2017-03-29T07:25:09.901537 #15581] INFO -- : Return Value:
::ffff:172.17.0.17 - - [29/Mar/2017:07:25:09 +0000] "GET /remote/cluster_start HTTP/1.1" 400 - 8.9617
[2017-03-29 07:25:09] INFO WEBrick::HTTPServer#start done.

We try to address this by doing two things:
A) We add a --wait switch to the cluster setup which should wait until
   the restart is complete.
B) We add a set of retries to the cluster start statement

While it is likely that either one of these be enough to close this
race, given the elusiveness of the problem (in CI upstream we hit
it twice in the last month), I prefer taking a more comprehensive
approach at closing this window.

Another option would have been to remove the cluster start exec
statement and simply add --start to the cluster setup call. This
approach seems to me like a smaller less invasive change. Since I'd like
to backport this issue to older releases as well, I prefer to not
change the setup code too much at this stage.

Change-Id: I7cdfcbced0031040e9f45ddba7389868bb3f59b2
Closes-Bug: #1677312